### ISSUE TITLE
Request: Change number of digits

### ISSUE THREAD

**Issue by Mopfus** [pvvx/ATC_MiThermometer#248]
Hello there. First of all, very nice work!
For me and my HomeAssistant Setup it would be really handy, if it would be possible to change the number of digits that are send. So choosing between 0.01, 0.1 and 1 would be great!
For my humidity, integers are fine. And for my temperature readings, 1 digit is enough.
Thank you in advance :-)

**Comment by Protoncek** [comment]
Yes, i agree, that would be nice. However, i just created a separate sensors in HA and you're done:


```
- platform: template
   sensors:
    room_temperature_bthome:
      friendly_name: Room temperature
      unique_id: ani_temperatura_bthome
      value_template: "{{states('sensor.room_7d93_temperature')| round(1)}}"
      unit_of_measurement: "°C"
      device_class: temperature

    room_humidity_bthome:
      friendly_name: Room humidity
      unique_id: ani_vlaga_bthome
      value_template: "{{states('sensor.room_7d93_humidity')| round(0)}}"
      unit_of_measurement: "%"
      device_class: humidity
```
