### ISSUE TITLE
Upgrade issue: No battery stats in home assistant after firmware version 4.3

### ISSUE THREAD

**Issue by Zephael86** [pvvx/ATC_MiThermometer#500]
Since firmware 4.3 and up I always have 100% battery in Home Assistant.

Story time:
I have multiple Xiaomi Mijia at home. Hardware revision B1.4.
Data is collected with the help of a gateway ESP32, programmed via ESPHome.

I am using them since 2021, nearly the beginning of the first pvvx fork.
Firmware update on the thermometers happens, whenever I replace the battery.
(Therefore I still have 3.7, 4.2, 4.3 and 4.7 at the moment.)
Then I open the Telink Flasher, connect to the device and upload the latest available firmware.
For a year now I do not even note down the firmware version, because the flasher is so convenient.

I did not realized this problem only after 6/10 devices always reports 100% battery.
Temperature and Humidity seems to work fine.

Example ESPHome config:
```
- platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:18:51:7D"
    #Dummy bindkey
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "Bathroom temperature"
    humidity:
      name: "Bathroom humidity"
    battery_level:
      name: "Bathroom battery"
```

Advertising Type on device: MIJIA (MIHOME)

I would also appreciate if you could compile an ATC_42.bin, so I can retest if the now 4.3 and up devices start to send battery info.
I tried to setup a build environment, but was not successful so far.
